#!/usr/bin/env perl
# Public domain.  (Originally written by Karl Berry, 2011.)
# This script does nothing but read TLPDB so we can work 
# on optimizing the inner loop, TLPOBJ::from_fh.

our $mydir;

BEGIN {
  $^W = 1;
  ($mydir = $0) =~ s,/[^/]*$,,;
  unshift (@INC, "$mydir/..");
}

use strict;
use TeXLive::TLPDB;

chomp (my $Master = `cd $mydir/../.. && pwd`);
my $tlpdb = TeXLive::TLPDB->new ("root" => $Master);
