# $OpenBSD$

COMMENT =		symbolic mathematics for Python

MODPY_EGG_VERSION =	0.7.1
DISTNAME =		sympy-${MODPY_EGG_VERSION}
CATEGORIES =		math

HOMEPAGE =		http://sympy.org

MAINTAINER =		Edd Barrett <edd@openbsd.org>

# BSD
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MASTER_SITES =		http://sympy.googlecode.com/files/

MODULES =		lang/python
RUN_DEPENDS =		devel/ipython

NO_REGRESS =		Yes

.include <bsd.port.mk>
