#!/usr/bin/env perl
# $Id: tlpdb2list 11096 2008-10-28 23:50:25Z preining $
# Copyright 2007, 2008 Norbert Preining
# This file is licensed under the GNU General Public License version 2
# or any later version.
# 
# Create list files from tlpdb.

BEGIN {
  $^W = 1;
  ($mydir = $0) =~ s,/[^/]*$,,;
  unshift (@INC, "$mydir/..");
}

use strict;

use TeXLive::TLPOBJ;
use TeXLive::TLPDB;
use Getopt::Long;
use Pod::Usage;
use TeXLive::TLUtils;
use File::Path;

my $opt_outputdir = "new-list";
my $help = 0;

TeXLive::TLUtils::process_logging_options();

GetOptions("outputdir=s" => \$opt_outputdir,
           "help|?" => \$help) or pod2usage(1);
		
pod2usage(-exitstatus => 0, -verbose => 2) if $help;
pod2usage(1) if ($#ARGV<0);

if (! -d $opt_outputdir) {
  mkpath ($opt_outputdir) or die "cannot mkdir $opt_outputdir: $!";
}	

die "cannot read tlpdb $ARGV[0]." if (! -r "$ARGV[0]");

my $tlpdb = new TeXLive::TLPDB (root => $ARGV[0]);
$tlpdb->generate_listfiles ($opt_outputdir);

__END__

=head1 NAME

tlpdb2list - generates list files from a TeX Live Package Database

=head1 SYNOPSIS

tlpdb2list [OPTION]... /path/to/installation/root/

=head1 OPTIONS

=over 4

=item B<-outputdir> I<output_dir>
Specifies the location where list files are created. Defaults to
C<./new-list>.

=back

The standard options C<-help>, C<-q>, and C<-v> are also accepted.
See the tlpfiles documentation for details.

=head1 DESCRIPTION

B<tlpdb2list> generates list files necessary for the installer from the
TeX Live Package Database found in the installation given on the
command line.

=head1 AUTHORS AND COPYRIGHT

This script and its documentation were written for the TeX Live
distribution (L<http://tug.org/texlive>) and both are licensed under the
GNU General Public License Version 2 or later.

=cut

### Local Variables:
### perl-indent-level: 2
### tab-width: 2
### indent-tabs-mode: nil
### End:
# vim:set tabstop=2: #
