# $OpenBSD: Makefile,v 1.6 2010/12/03 11:44:26 ajacoutot Exp $

COMMENT =	readline-a-like library for TTYtter

MODULES =	cpan
DISTNAME =	Term-ReadLine-TTYtter-1.2
CATEGORIES =	devel
USE_GROFF =	Yes

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

CPAN_AUTHOR =			CKAISER

.include <bsd.port.mk>
