# $OpenBSD: Makefile.template,v 1.61 2012/03/29 13:41:58 sthen Exp $

COMMENT =		zathura document viewer meta-package
PKGNAME =		zathura-0.2.0

RUN_DEPENDS =		textproc/zathura \
			textproc/zathura/plugins/zathura-pdf-poppler

.include <bsd.port.mk>
