# $OpenBSD: Makefile,v 1.17 2012/02/21 22:34:19 sthen Exp $

CATEGORIES ?=		textproc x11

MAINTAINER ?=		Abel Abraham Camarillo Ojeda <acamari@the00z.org>

# MIT
PERMIT_PACKAGE_CDROM ?=	Yes
PERMIT_PACKAGE_FTP ?=	Yes
PERMIT_DISTFILES_CDROM ?=Yes
PERMIT_DISTFILES_FTP ?=	Yes

USE_GMAKE ?=	Yes
USE_GROFF ?=	Yes
